In [1]:
import numpy as np
print(np.__version__)


2.0.1


In [6]:
import pandas as pd   
import numpy as np   

numbers = pd.Series(np.random.randint(0, 100, 1000))
print(numbers.head())


0    93
1    17
2    76
3    41
4    62
dtype: int32


In [ ]:
import pandas as pd
import numpy as np

students = pd.Series([1,2,3,4,5,6,7,8,9,10])
students.loc[10] = 20
students

IndexError: iloc cannot enlarge its target object

In [25]:
import pandas as pd
student1 = pd.Series({'Name': 'Alice', 'Age': 23, 'Score': 85})
student2 = pd.Series({'Name': 'Bob', 'Age': 24, 'Score': 90})
student3 = pd.Series({'Name': 'Charlie', 'Age': 22, 'Score': 88})
df = pd.DataFrame([student1, student2, student3])
df.index = ['Girl', 'Boy', 'Bio']
df.loc[:, ['Name', 'Score']]
df.drop(['Girl'])

,Name,Age,Score
Boy,Bob,24,90
Bio,Charlie,22,88


In [26]:
import pandas as pd
students = ['Kanza', 'Ali', 'Sara', 'None']
pd.Series(students)


0    Kanza
1      Ali
2     Sara
3     None
dtype: object

In [30]:
import pandas as pd
numbers = [1,2,3,4,5,6,7,8,9,None]
pd.Series(numbers)
total = pd.Series(numbers).sum()        # default skipna=True
print(total)


45.0


In [31]:
import pandas as pd
students = [("Alice","Brown"), ("Jack", "White"), ("Molly", "Green")]
pd.Series(students)

0    (Alice, Brown)
1     (Jack, White)
2    (Molly, Green)
dtype: object

In [35]:
import pandas as pd
students_classes = {'Alice': 'Physics',
                   'Jack': 'Chemistry',
                   'Molly': 'English',
                   'Sam': 'History'}
s = pd.Series(students_classes)
s.iloc[3]

'History'

In [40]:
import pandas as pd
class_code = {99: 'Physics',
              100: 'Chemistry',
              101: 'English',
              102: 'History'}
s = pd.Series(class_code)
s.iloc[0]  # Accessing the value at index 2 (English)

'Physics'

In [42]:
import pandas as pd
grades = pd.Series([90, 80, 70, 60])

average = grades.mean()
print(average)

75.0


In [ ]:
import pandas as pd
import numpy as np

numbers = pd.Series(np.random.randint(0,1000,10000))

print(numbers.head())




0    689
1    542
2      1
3    519
4    635
dtype: int32


UsageError: Line magic function `%%timeit` not found.


In [56]:
%%timeit -n 100
total = np.sum(numbers)
total/len(numbers)

28.7 μs ± 7.19 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [59]:
import pandas as pd
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}
frame = pd.DataFrame(data)
frame



,state,year,pop
0,Ohio,2000,1.5
1,Ohio,2001,1.7
2,Ohio,2002,3.6
3,Nevada,2001,2.4
4,Nevada,2002,2.9


In [60]:
import pandas as pd
s = pd.Series([1, 2, 3, 4, 5])
new_s = s.mask(s >2, 0)
print(new_s)


0    1
1    2
2    0
3    0
4    0
dtype: int64


In [64]:
import pandas as pd
import numpy as np
df = pd.read_csv(r'C:\Users\kanza\Downloads\class_grades.csv')
df.head(10)

,Prefix,Assignment,Tutorial,Midterm,TakeHome,Final
0,5,57.14,34.09,64.38,51.48,52.50
1,8,95.05,105.49,67.50,99.07,68.33
2,8,83.70,83.17,NaN,63.15,48.89
3,7,NaN,NaN,49.38,105.93,80.56
4,8,91.32,93.64,95.00,107.41,73.89
5,7,95.00,92.58,93.12,97.78,68.06
6,8,95.05,102.99,56.25,99.07,50.00
7,7,72.85,86.85,60.00,NaN,56.11
8,8,84.26,93.10,47.50,18.52,50.83
9,7,90.10,97.55,51.25,88.89,63.61


In [66]:
import pandas as pd
df = pd.read_csv(r'C:\Users\kanza\Downloads\class_grades.csv')
df.dropna().head()

,Prefix,Assignment,Tutorial,Midterm,TakeHome,Final
0,5,57.14,34.09,64.38,51.48,52.50
1,8,95.05,105.49,67.50,99.07,68.33
4,8,91.32,93.64,95.00,107.41,73.89
5,7,95.00,92.58,93.12,97.78,68.06
6,8,95.05,102.99,56.25,99.07,50.00


In [68]:
import pandas as pd
df = pd.read_csv(r'C:\Users\kanza\Downloads\class_grades.csv')
df = df.fillna(method='ffill')
df.head(20)

C:\Users\kanza\AppData\Local\Temp\ipykernel_25576\2359035671.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df = df.fillna(method='ffill')


,Prefix,Assignment,Tutorial,Midterm,TakeHome,Final
0,5,57.14,34.09,64.38,51.48,52.50
1,8,95.05,105.49,67.50,99.07,68.33
2,8,83.70,83.17,67.50,63.15,48.89
3,7,83.70,83.17,49.38,105.93,80.56
4,8,91.32,93.64,95.00,107.41,73.89
5,7,95.00,92.58,93.12,97.78,68.06
6,8,95.05,102.99,56.25,99.07,50.00
7,7,72.85,86.85,60.00,99.07,56.11
8,8,84.26,93.10,47.50,18.52,50.83
9,7,90.10,97.55,51.25,88.89,63.61


In [73]:
import pandas as pd
df = pd.read_csv(r"C:\Users\kanza\Downloads\log.csv")
df = df.set_index('time')
df = df.sort_index()
df.head()

,user,video,playback position,paused,volume
time,,,,,
1469974424,cheryl,intro.html,5,False,10.0
1469974424,sue,advanced.html,23,False,10.0
1469974454,sue,advanced.html,24,NaN,NaN
1469974454,cheryl,intro.html,6,NaN,NaN
1469974484,cheryl,intro.html,7,NaN,NaN


In [ ]:
import pandas as pd
df = pd.read_csv(r"C:\Users\kanza\Downloads\log.csv")
df = df.set_index('time')
df = df.sort_index()
df = df.fillna(method='ffill')
df.head()

In [75]:
import pandas as pd
df = pd.DataFrame({'A': [1, 1, 2, 3, 4],
                   'B': [3, 6, 3, 8, 9],
                   'C': ['a', 'b', 'c', 'd', 'e']})
df
df.replace(1, 100)

,A,B,C
0,100,3,a
1,100,6,b
2,2,3,c
3,3,8,d
4,4,9,e


In [76]:
import pandas as pd
df = pd.DataFrame({'A': [1, 1, 2, 3, 4],
                   'B': [3, 6, 3, 8, 9],
                   'C': ['a', 'b', 'c', 'd', 'e']})
df
df.replace([1, 3], [100, 300])

,A,B,C
0,100,300,a
1,100,6,b
2,2,300,c
3,300,8,d
4,4,9,e


In [78]:
import pandas as pd
students_scores = {'Alice': 'Physics',
                   'Jack': 'Chemistry',
                   'Molly': 'English'}
s = pd.Series(students_scores)
s.index


Index(['Alice', 'Jack', 'Molly'], dtype='object')

In [79]:
import pandas as pd
s = pd.Series(['Physics', 'Chemistry', 'English'], index=['Alice', 'Jack', 'Molly'])
s

Alice      Physics
Jack     Chemistry
Molly      English
dtype: object

In [ ]:
import pandas as pd
students_classes = {'Alice': 'Physics',
                   'Jack': 'Chemistry',
                   'Molly': 'English',
                   'Sam': 'History'}
s = pd.Series(students_classes)
s.iloc[3]

C:\Users\kanza\AppData\Local\Temp\ipykernel_25576\750597375.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[0]


'Physics'

In [86]:
import pandas as pd
import pandas as pd
df = pd.read_csv(r"C:\Users\kanza\Downloads\Admission_Predict.csv", index_col=0)
df.head()

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
Serial No.,,,,,,,,
1,337,118,4,4.5,4.5,9.65,1,0.92
2,324,107,4,4.0,4.5,8.87,1,0.76
3,316,104,3,3.0,3.5,8.00,1,0.72
4,322,110,3,3.5,2.5,8.67,1,0.80
5,314,103,2,2.0,3.0,8.21,0,0.65


In [87]:
import pandas as pd
import pandas as pd
df = pd.read_csv(r"C:\Users\kanza\Downloads\Admission_Predict.csv")
df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65


In [88]:
df['Serial Number'] = df.index
df = df.set_index('Chance of Admit ')
df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Serial Number
Chance of Admit,,,,,,,,,
0.92,1,337,118,4,4.5,4.5,9.65,1,0
0.76,2,324,107,4,4.0,4.5,8.87,1,1
0.72,3,316,104,3,3.0,3.5,8.00,1,2
0.80,4,322,110,3,3.5,2.5,8.67,1,3
0.65,5,314,103,2,2.0,3.0,8.21,0,4


In [ ]:
# import pandas as pd
# df = pd.read_csv(r"C:\Users\kanza\Downloads\census.csv")
# df=df[df['SUMLEV'] == 50]
# df.head()
C:\Users\kanza\Downloads\Ex_Files_Python_EssT\Ex_Files_Python_EssT\Exercise Files\exercise_files\oop.py




,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411


In [120]:
import pandas as pd
def proportion_of_education():
    df = pd.read_cvs(r"C:\Users\kanza\Downloads\NISPUF17.csv")
print(df.head())




   SUMLEV  REGION  DIVISION  STATE  COUNTY   STNAME         CTYNAME  \
1      50       3         6      1       1  Alabama  Autauga County   
2      50       3         6      1       3  Alabama  Baldwin County   
3      50       3         6      1       5  Alabama  Barbour County   
4      50       3         6      1       7  Alabama     Bibb County   
5      50       3         6      1       9  Alabama   Blount County   

   CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010  ...  RDOMESTICMIG2011  \
1          54571              54571            54660  ...          7.242091   
2         182265             182265           183193  ...         14.832960   
3          27457              27457            27341  ...         -4.728132   
4          22915              22919            22861  ...         -5.527043   
5          57322              57322            57373  ...          1.807375   

   RDOMESTICMIG2012  RDOMESTICMIG2013  RDOMESTICMIG2014  RDOMESTICMIG2015  \
1         -2.915927  

In [132]:
import pandas as pd

df = pd.read_csv(r"C:\Users\kanza\Downloads\NISPUF17.csv", nrows=100)

def proportion_of_education():
    educ = df['EDUC1'].dropna()
    total = len(educ)

    proportions = {
        "less than high school": (educ == 1).sum() / total,
        "high school": (educ == 2).sum() / total,
        "more than high school but not college": (educ == 3).sum() / total,
        "college": (educ == 4).sum() / total,
    }
    return proportions
print(proportion_of_education())


{'less than high school': np.float64(0.06), 'high school': np.float64(0.17), 'more than high school but not college': np.float64(0.29), 'college': np.float64(0.48)}


In [135]:
import pandas as pd
def average_influenza_doses():
    df = pd.read_csv(r"C:\Users\kanza\Downloads\NISPUF17.csv", nrows=100)
    doses = df[['P_NUMFLU', 'CBF_01']].dropna()
    yes_group = doses[doses['CBF_01'] == 1]
    no_group = doses[doses['CBF_01'] == 2]
    yes_avg = yes_group['P_NUMFLU'].mean()
    no_avg = no_group['P_NUMFLU'].mean()
    return (yes_avg, no_avg)
print(average_influenza_doses())

(np.float64(2.152173913043478), np.float64(1.6))


In [ ]:
def corr_chickenpox():
    import scipy.stats as stats
    import numpy as np
    import pandas as pd
    
    # Load the real dataset
    df = pd.read_csv("assets/NISPUF17.csv")  # make sure the path is correct

    # Filter valid rows: HAD_CPOX must be 1 or 2, and P_NUMVRC must not be NaN
    df = df[(df['HAD_CPOX'].isin([1, 2])) & (df['P_NUMVRC'].notna())]

    # Run the correlation between the two columns
    corr, pval = stats.pearsonr(df["HAD_CPOX"], df["P_NUMVRC"])

    return corr, pval


In [ ]:
import pandas as pd
class_code = {22: 'Physics',
              100: 'Chemistry',
              101: 'English',
              102: 'History'}
s = pd.Series(class_code)
s[0]

KeyError: 0

In [116]:
import numpy as np
data = [[1,2,3,4,4], [5,6,7,8,9]]
print(np.array(data))

[[1 2 3 4 4]
 [5 6 7 8 9]]


In [ ]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [5]:
import numpy as np
arr2 = np.array([1, 2, 3])
print(arr2.mean())  # ✅ Correct: will output the average (2.0)
print(arr2.std())   # ✅ Correct: will output the standard deviation (0.816496580927726)
print(arr2.var())   # ✅ Correct: will output the variance (0.6666666666666666) 
print(arr2.sum())   # ✅ Correct: will output the sum (6)
print(arr2.min())   # ✅ Correct: will output the minimum value (1)


2.0
0.816496580927726
0.6666666666666666
6
1


In [16]:
import numpy as np
ma = np.array([[ 0.9526, -0.246 , -0.8856],
                     [ 0.5639,  0.2379,  0.9104]])

print(ma * 10)

print(ma.shape)  # ✅ Correct: will output the shape of the array ((2, 3))

print(ma.dtype)
print(ma.ndim)  # ✅ Correct: will output the number of dimensions (2)



[[ 9.526 -2.46  -8.856]
 [ 5.639  2.379  9.104]]
(2, 3)
float64
2


In [ ]:
import numpy as np
ma = np.array([[ 0.9526, -0.246 , -0.8856],
                     [ 0.5639,  0.2379,  0.9104]])
ma2 = np.array([[ 0.9050, -0.290 , -0.9000],
                     [ 0.5900,  0.9505,  0.49404]])
print(ma + ma2)  # ✅ Correct: will output the element-wise sum of the two arrays
print(ma - ma2)  # ✅ Correct: will output the element-wise difference of the two arrays
print(ma * ma2)  # ✅ Correct: will output the element-wise product of the two arrays
print(ma / ma2)  # ✅ Correct: will output the element-wise division of the two arrays
print(ma * 0.5)

[[ 1.8576  -0.536   -1.7856 ]
 [ 1.1539   1.1884   1.40444]]
[[ 0.0476   0.044    0.0144 ]
 [-0.0261  -0.7126   0.41636]]
[[0.862103   0.07134    0.79704   ]
 [0.332701   0.22612395 0.44977402]]
[[1.05259669 0.84827586 0.984     ]
 [0.95576271 0.25028932 1.84276577]]
[[ 0.4763  -0.123   -0.4428 ]
 [ 0.28195  0.11895  0.4552 ]]


In [17]:
import numpy as np
myz = np.zeros((3, 4))  # ✅ Correct: creates a 3x4 array filled with zeros
print(myz)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
memty = np.empty((2, 3))  # ✅ Correct: creates a 2x3 array with uninitialized values
print(memty)  # ✅ Correct: will output the uninitialized values in the array

[[0.9526 0.246  0.8856]
 [0.5639 0.2379 0.9104]]


In [33]:
mrange = np.arange(10)  # ✅ Correct: creates an array with values from 0 to 9
print(mrange)  # ✅ Correct: will output the array [0 1 2 3 4 5 6 7 8 9]
mrange[5:9] = 12
print(mrange)  # ✅ Correct: will output the modified array [0 1 2 3 4 12 6 7 8 9]
maslice = mrange[5:9]  # ✅ Correct: creates a slice of the array from index 5 to 8
print(maslice)  # ✅ Correct: will output the slice [12 6 7 8]
maslice[1] = 89  # ✅ Correct: sets the values in the slice to 0
print(maslice)  # ✅ Correct: will output the modified array [0 1 2 3 4 12 6 7 8 9]
print(mrange)  # ✅ Correct: will output the modified array [0 1 2 3 4 12 89 7 8 9]


[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 12 12 12 12  9]
[12 12 12 12]
[12 89 12 12]
[ 0  1  2  3  4 12 89 12 12  9]


In [34]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d.ndim)  # ✅ Correct: will output the number of dimensions (2)

2


In [47]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(names)  # ✅ Correct: will output the unique names in the array ['Bob' 'Joe' 'Will']
data = np.random.rand(7, 4)
print(data)  # ✅ Correct: will output the random data array
names == 'Bob'
print(names == 'Bob')  # ✅ Correct: will output a boolean array indicating where the name is 'Bob'    
print(data[names == 'Bob'])  # ✅ Correct: will output the rows of data where the name is 'Bob'
print(data[names == 'Bob', 2:])  # ✅ Correct: will output the rows of data where the name is 'Bob' and columns from index 2 onwards
print(data[names == 'Bob', 3])  # ✅ Correct: will output the values in the 3rd column where the name is 'Bob'

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[0.54089059 0.67782558 0.56272534 0.51722021]
 [0.10646255 0.71151877 0.25505572 0.37714161]
 [0.17889973 0.57249673 0.92518282 0.45482909]
 [0.22961765 0.19847333 0.09057419 0.77958687]
 [0.38370151 0.89620684 0.5909723  0.89075344]
 [0.06402348 0.54407173 0.80313466 0.44677043]
 [0.02658556 0.3543761  0.86163518 0.01334374]]
[ True False False  True False False False]
[[0.54089059 0.67782558 0.56272534 0.51722021]
 [0.22961765 0.19847333 0.09057419 0.77958687]]
[[0.56272534 0.51722021]
 [0.09057419 0.77958687]]
[0.51722021 0.77958687]


In [50]:
import numpy as np

# Generate 1000 random numbers from a standard normal distribution
large_arr = np.random.randn(1000)

# Sort the array
large_arr.sort()

# Calculate the 5% quantile
quantile_5 = large_arr[int(0.05 * len(large_arr))]
print(quantile_5)

-1.7233831265764785


In [54]:
import pandas as pd
import numpy as np
record1 = pd.Series({'Name': 'Alice',
                        'Class': 'Physics',
                        'Score': 85})
record2 = pd.Series({'Name': 'Jack',
                        'Class': 'Chemistry',
                        'Score': 82})
record3 = pd.Series({'Name': 'Helen',
                        'Class': 'Biology',
                        'Score': 90})

df = pd.DataFrame([record1, record2, record3])
df.head()


,Name,Class,Score
0,Alice,Physics,85
1,Jack,Chemistry,82
2,Helen,Biology,90


In [83]:
import pandas as pd
import numpy as np
students = [{'Name': 'Alice',
              'Class': 'Physics',
              'Score': 85},
            {'Name': 'Jack',
             'Class': 'Chemistry',
             'Score': 82},
            {'Name': 'Helen',
             'Class': 'Biology',
             'Score': 90}]
df = pd.DataFrame(students, index=['school1', 'school2', 'school1'])
# df.loc['school1']
# type(df.loc['school2'])
# type(df.loc['school1'])
# type(df.loc['school1'])
# df.loc['school1', 'Name']
df.T.loc['Name']
print(type(df.loc['school1', 'Name']))
print(type(df.loc['school1']))
df.loc[:,['Name', 'Score']]
df.drop('school1')

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>


,Name,Class,Score
school2,Jack,Chemistry,82


In [79]:
import pandas as pd
import numpy as np
students = [{'Name': 'Alice',
              'Class': 'Physics',
              'Score': 85},
            {'Name': 'Jack',
             'Class': 'Chemistry',
             'Score': 82},
            {'Name': 'Helen',
             'Class': 'Biology',
             'Score': 90}]
df = pd.DataFrame(students)
# df.loc['school1']
# type(df.loc['school2'])
# type(df.loc['school1'])
# type(df.loc['school1'])
# df.loc['school1', 'Name']
# df.T.loc['Name']
# df['Name']
print(type(df.loc['school1'])) #should be a DataFrame
print(type(df.loc['school1', 'Name']))
 #should be a Series

KeyError: 'school1'